List = ['Cookwinks', 'GO Daddy', 'Pepperfry', 'Zomato', 'Puma', 'Mercedes']
# print(List[1:3])
# print(List[1][3:len(List[1])])
# print(List[2][0:-3])
# print(List[2][-3:len(List[2])])
# List.sort()
# print(List)
# List.reverse()
# print(List)
# List.append('Motorola')
# print(List)
# List.insert(2,'Casio')
# print(List)
# print(List.pop(3))   # pop returns value 
# print(List)
# List.remove('Pepperfry')
print(List.remove('Pepperfry'))